name = "PhyloClustering"
uuid = "2e4ec7c6-185f-4bfd-8419-ce336ea983f6"
authors = ["Yibo Kong <ykong42@wisc.edu> and contributors"]
version = "0.3.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Clustering = "0.15.5"
Combinatorics = "1.0.2"
Distances = "0.10.10"
Formatting = "0.4.2"
GaussianMixtures = "0.3.8"
MultivariateStats = "0.10.2"
ParallelKMeans = "1.1.0"
PhyloNetworks = "0.16.3"
StatsBase = "0.33.21"
julia = "1.7, 1.8, 1.9, 1.10"

[extras]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor", "Revise", "StableRNGs"]
